### ISSUE TITLE
change background dynamically

### ISSUE THREAD

**Issue by jacobbutton** [snics/ng2-avatar#1]
Anyway to add the ability to update the background color, like after an a sync call to pull an object from the database that's storing a color attribute?

**Comment by snics** [comment]
Hi jacobbutton,

you can set an own background like this:
```javascript
 <avatar [email]="email" [displayType]="'circle'" background="#000000"></avatar>
```
or your set dynamically over an input data binding like this:
```javascript
 <avatar [email]="email" [displayType]="'circle'" (background)="colorHandler()"></avatar>
```


Could I answer your question?
