### ISSUE TITLE
It only seems to handle a single letter.  I'd like initials  e.g. NR

### ISSUE THREAD

**Issue by nickraphael** [snics/ng2-avatar#11]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

**Comment by snics** [comment]
Hi @nickraphael, I don't know exactly what you mean. Please give me more infos and wrote more infos in the bug report template. thx!

**Comment by snics** [comment]
Hi @nickraphael I will close the issue now please give me feedback if you need help.
