### ISSUE TITLE
Printing email address in the console log

### ISSUE THREAD

**Issue by yogeshbansal** [snics/ng2-avatar#7]
ng2 avatar code is printing the email address in the console. It will be great if we can remove console statement from the code.

**Comment by yogeshbansal** [comment]
looks like it fixed with the latest version

**Comment by snics** [comment]
@yogeshbansal yes i fix this in version [2.2.0](https://github.com/snics/ng2-avatar/blob/master/CHANGELOG.md#220-2017-12-20)
