### ISSUE TITLE
angular universal support - (Error: SyntaxError: Unexpected token import)

### ISSUE THREAD

**Issue by AnthonyNahas** [snics/ng2-avatar#8]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?
OS : macOs HighSierra 
### Versions
Angular: 1.6.8
Node: local (8.9.4) cloud (6xx)
Npm: local 5.6.0 - cloud (4xx)

### Repro steps
Deploying to cloud is not working!
Since node v6 does not support import and export statements, all js files of this module
should be transpiled to es5, and converting these syntax e.g from import to require..

### The log given by the failure
```sh
Error: Error occurred while parsing your function triggers.

/Users/x/myproject/node_modules/ng2-avatar/module/component/avatar.component.js:2
import { Component, Input } from '@angular/core';
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.L0VR (/
```

### Desired functionality
the module should not use import statement!
to support all nodes versions for SSR (server side rendering), the js files should be transpiled to es5 and use require instead of import statements...
 

**note**: [here is a link on how I fixed similar issues...](https://github.com/SebastianM/angular-google-maps/issues/1052)

**Comment by AnthonyNahas** [comment]
[#9](https://github.com/snics/ng2-avatar/pull/9#event-1547772587)

**Comment by snics** [comment]
@AnthonyNahas thank you for your error report and pull request. The new version is now live (2.3.0)
